---
apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: library
  lifecycle: production
  owner: List_custom_t348_cds_sdk@3ds.com
  experience: data

metadata:
  json_schema: "https://github.com/mdsol/platform-standards/tree/master/schemas/v1alpha1.schema.json" # This is a constant, just leave as is.
  name: dataconnect-library-python
  title: Data Connect Library for Python
  description: Python library built by Medidata for connecting to Data Connect and programmatically querying and retrieving data.
  teams:
    - number: 348
      name: Team 348 (SDK)
      email: List_custom_t348_cds_sdk@3ds.com
  people:
    - role: technical owner
      email: List_custom_t348_cds_sdk@3ds.com
    - role: engineering manager
      email: List_custom_t348_cds_sdk@3ds.com

  annotations:
    product: Data Connect Library for Python
